// Sprint 7: Shop Data — 35 items across 6 categories
import type { ShopItem, ShopCategory } from '../types/game';

export const SHOP_ITEMS: ShopItem[] = [
  // === OFFICE UPGRADES (7 items) ===
  {
    id: 'office-desk-pro',
    name: 'Pro Desk',
    description: 'Ergonomic standing desk with built-in cable management. +10% XP from tickets.',
    category: 'office-upgrade',
    cost: 500,
    requiredLevel: 1,
    icon: '🪑',
    buff: { type: 'xp_multiplier', value: 1.10, isFlat: false },
    maxPurchases: 1,
    officeUpgrade: 'desk_pro',
  },
  {
    id: 'office-monitor-ultrawide',
    name: 'Ultrawide Monitor',
    description: '49" curved ultrawide display. +5 min time extension on all tickets.',
    category: 'office-upgrade',
    cost: 800,
    requiredLevel: 2,
    icon: '🖥️',
    buff: { type: 'time_extension', value: 5, isFlat: true },
    maxPurchases: 1,
    officeUpgrade: 'monitor_ultrawide',
  },
  {
    id: 'office-chair-ergo',
    name: 'Ergonomic Chair',
    description: 'Herman Miller Aeron. +15% reputation from completed tickets.',
    category: 'office-upgrade',
    cost: 1200,
    requiredLevel: 3,
    icon: '💺',
    buff: { type: 'reputation_multiplier', value: 1.15, isFlat: false },
    maxPurchases: 1,
    officeUpgrade: 'chair_ergo',
  },
  {
    id: 'office-server-rack',
    name: 'Personal Server Rack',
    description: '42U rack in your office. +20% credit rewards from tickets.',
    category: 'office-upgrade',
    cost: 2500,
    requiredLevel: 5,
    icon: '🗄️',
    buff: { type: 'credit_multiplier', value: 1.20, isFlat: false },
    maxPurchases: 1,
    officeUpgrade: 'server_rack',
  },
  {
    id: 'office-whiteboard',
    name: 'Smart Whiteboard',
    description: 'Digital whiteboard with network topology templates. +10% XP and credits.',
    category: 'office-upgrade',
    cost: 3000,
    requiredLevel: 4,
    icon: '📋',
    buff: { type: 'xp_multiplier', value: 1.10, isFlat: false },
    maxPurchases: 1,
    officeUpgrade: 'whiteboard',
  },
  {
    id: 'office-coffee-bar',
    name: 'Espresso Bar',
    description: 'Professional espresso machine. Grants coffee boost: +3 min time extension, 30 min cooldown.',
    category: 'office-upgrade',
    cost: 4000,
    requiredLevel: 6,
    icon: '☕',
    buff: { type: 'time_extension', value: 3, isFlat: true },
    maxPurchases: 1,
    officeUpgrade: 'coffee_bar',
  },
  {
    id: 'office-couch',
    name: 'Executive Couch',
    description: 'Italian leather couch. Passive reputation regeneration while idle.',
    category: 'office-upgrade',
    cost: 10000,
    requiredLevel: 8,
    icon: '🛋️',
    buff: { type: 'reputation_multiplier', value: 1.25, isFlat: false },
    maxPurchases: 1,
    officeUpgrade: 'executive_couch',
  },

  // === CERTIFICATIONS (6 items) ===
  {
    id: 'cert-ccna',
    name: 'CCNA Certification',
    description: 'Cisco Certified Network Associate. +15% XP from routing/switching tickets.',
    category: 'certification',
    cost: 500,
    requiredLevel: 1,
    icon: '📜',
    buff: { type: 'xp_multiplier', value: 1.15, isFlat: false },
    maxPurchases: 1,
  },
  {
    id: 'cert-ccnp',
    name: 'CCNP Certification',
    description: 'Cisco Certified Network Professional. +20% credit rewards from all tickets.',
    category: 'certification',
    cost: 1500,
    requiredLevel: 4,
    icon: '🎓',
    buff: { type: 'credit_multiplier', value: 1.20, isFlat: false },
    maxPurchases: 1,
  },
  {
    id: 'cert-security-plus',
    name: 'Security+ Certification',
    description: 'CompTIA Security+. +25% reputation from security tickets.',
    category: 'certification',
    cost: 800,
    requiredLevel: 3,
    icon: '🛡️',
    buff: { type: 'reputation_multiplier', value: 1.25, isFlat: false },
    maxPurchases: 1,
  },
  {
    id: 'cert-aws-sa',
    name: 'AWS Solutions Architect',
    description: 'AWS Certified Solutions Architect. +20% XP from systems/automation tickets.',
    category: 'certification',
    cost: 2000,
    requiredLevel: 5,
    icon: '☁️',
    buff: { type: 'xp_multiplier', value: 1.20, isFlat: false },
    maxPurchases: 1,
  },
  {
    id: 'cert-cissp',
    name: 'CISSP Certification',
    description: 'Certified Information Systems Security Professional. +30% reputation from all tickets.',
    category: 'certification',
    cost: 5000,
    requiredLevel: 7,
    icon: '🔐',
    buff: { type: 'reputation_multiplier', value: 1.30, isFlat: false },
    maxPurchases: 1,
  },
  {
    id: 'cert-ccie',
    name: 'CCIE Certification',
    description: 'Cisco Certified Internetwork Expert. +35% XP and credits from all tickets.',
    category: 'certification',
    cost: 8000,
    requiredLevel: 8,
    icon: '🏆',
    buff: { type: 'xp_multiplier', value: 1.35, isFlat: false },
    maxPurchases: 1,
  },

  // === TOOLS (6 items) ===
  {
    id: 'tool-cable-tester',
    name: 'Cable Tester Pro',
    description: 'Fluke cable certifier. +10% hint discount on switching tickets.',
    category: 'tool',
    cost: 300,
    requiredLevel: 1,
    icon: '🔌',
    buff: { type: 'hint_discount', value: 10, isFlat: true },
    maxPurchases: 1,
  },
  {
    id: 'tool-wifi-analyzer',
    name: 'WiFi Analyzer',
    description: 'Ekahau Sidekick spectrum analyzer. +15% XP from wireless tickets.',
    category: 'tool',
    cost: 750,
    requiredLevel: 2,
    icon: '📡',
    buff: { type: 'xp_multiplier', value: 1.15, isFlat: false },
    maxPurchases: 1,
  },
  {
    id: 'tool-protocol-analyzer',
    name: 'Protocol Analyzer',
    description: 'Wireshark certified capture appliance. +10 min time extension on routing tickets.',
    category: 'tool',
    cost: 1200,
    requiredLevel: 4,
    icon: '🔍',
    buff: { type: 'time_extension', value: 10, isFlat: true },
    maxPurchases: 1,
  },
  {
    id: 'tool-sfp-tester',
    name: 'SFP Tester',
    description: 'Optical power meter and SFP validator. +15% credit from switching tickets.',
    category: 'tool',
    cost: 600,
    requiredLevel: 3,
    icon: '💡',
    buff: { type: 'credit_multiplier', value: 1.15, isFlat: false },
    maxPurchases: 1,
  },
  {
    id: 'tool-pen-test-kit',
    name: 'Pen Test Kit',
    description: 'Portable penetration testing toolkit. +25% reputation from security tickets.',
    category: 'tool',
    cost: 3500,
    requiredLevel: 6,
    icon: '💻',
    buff: { type: 'reputation_multiplier', value: 1.25, isFlat: false },
    maxPurchases: 1,
  },
  {
    id: 'tool-datacenter-toolkit',
    name: 'Datacenter Toolkit',
    description: 'Full datacenter maintenance toolkit. +20% XP and credits from HA tickets.',
    category: 'tool',
    cost: 6000,
    requiredLevel: 7,
    icon: '🧰',
    buff: { type: 'xp_multiplier', value: 1.20, isFlat: false },
    maxPurchases: 1,
  },

  // === CONSUMABLES (6 items) ===
  {
    id: 'consumable-energy-drink',
    name: 'Energy Drink',
    description: 'Doubles XP for the next ticket completed (one use).',
    category: 'consumable',
    cost: 50,
    requiredLevel: 1,
    icon: '🧃',
    consumable: { type: 'xp_multiplier', value: 2.0, isFlat: false, duration: 1800 },
    maxPurchases: 10,
  },
  {
    id: 'consumable-coffee-premium',
    name: 'Premium Coffee',
    description: '+10 min time extension for the next ticket (one use).',
    category: 'consumable',
    cost: 75,
    requiredLevel: 1,
    icon: '☕',
    consumable: { type: 'time_extension', value: 10, isFlat: true, duration: 3600 },
    maxPurchases: 5,
  },
  {
    id: 'consumable-mentor-session',
    name: 'Mentor Session',
    description: 'Free hints for the next ticket. Hint cost reduced to 0.',
    category: 'consumable',
    cost: 150,
    requiredLevel: 2,
    icon: '👨‍🏫',
    consumable: { type: 'hint_discount', value: 100, isFlat: true, duration: 3600 },
    maxPurchases: 3,
  },
  {
    id: 'consumable-lucky-charm',
    name: 'Lucky Network Charm',
    description: '+50% credit reward for the next ticket completed.',
    category: 'consumable',
    cost: 200,
    requiredLevel: 3,
    icon: '🍀',
    consumable: { type: 'credit_multiplier', value: 1.50, isFlat: false, duration: 1800 },
    maxPurchases: 5,
  },
  {
    id: 'consumable-pizza-party',
    name: 'Team Pizza Party',
    description: '+30% reputation and credits for the next ticket.',
    category: 'consumable',
    cost: 500,
    requiredLevel: 4,
    icon: '🍕',
    consumable: { type: 'reputation_multiplier', value: 1.30, isFlat: false, duration: 1800 },
    maxPurchases: 3,
  },
  {
    id: 'consumable-overtime-boost',
    name: 'Overtime Boost',
    description: '+100% all rewards for the next ticket (24h duration).',
    category: 'consumable',
    cost: 1000,
    requiredLevel: 6,
    icon: '⚡',
    consumable: { type: 'xp_multiplier', value: 2.0, isFlat: false, duration: 86400 },
    maxPurchases: 2,
  },

  // === COSMETICS (6 items) ===
  {
    id: 'cosmetic-nameplate',
    name: 'Custom Nameplate',
    description: 'Personalized desk nameplate with your title. Bragging rights only.',
    category: 'cosmetic',
    cost: 100,
    requiredLevel: 1,
    icon: '🏷️',
    maxPurchases: 1,
  },
  {
    id: 'cosmetic-rgb-keyboard',
    name: 'RGB Keyboard',
    description: 'Programmable mechanical keyboard with custom lighting effects.',
    category: 'cosmetic',
    cost: 250,
    requiredLevel: 2,
    icon: '⌨️',
    maxPurchases: 1,
  },
  {
    id: 'cosmetic-plant-bonsai',
    name: 'Bonsai Tree',
    description: 'Digital bonsai that grows with your career. Changes appearance per floor.',
    category: 'cosmetic',
    cost: 500,
    requiredLevel: 3,
    icon: '🎋',
    maxPurchases: 1,
  },
  {
    id: 'cosmetic-neon-sign',
    name: 'Neon Sign',
    description: 'Custom neon sign for your office wall. "Trust but verify" in glowing letters.',
    category: 'cosmetic',
    cost: 1000,
    requiredLevel: 5,
    icon: '💡',
    maxPurchases: 1,
  },
  {
    id: 'cosmetic-golden-cable',
    name: 'Golden Ethernet Cable',
    description: 'Show off your wealth with a gold-plated Cat8 cable. Catches the light beautifully.',
    category: 'cosmetic',
    cost: 3000,
    requiredLevel: 7,
    icon: '✨',
    maxPurchases: 1,
  },
  {
    id: 'cosmetic-hologram-globe',
    name: 'Holographic Globe',
    description: '3D holographic network topology globe. The ultimate status symbol.',
    category: 'cosmetic',
    cost: 7500,
    requiredLevel: 8,
    icon: '🌐',
    maxPurchases: 1,
  },

  // === SPECIALTY (4 items) ===
  {
    id: 'specialty-uptime-insurance',
    name: 'Uptime Insurance',
    description: 'One free incident forgiveness. Prevents one reputation penalty from downtime.',
    category: 'specialty',
    cost: 2000,
    requiredLevel: 3,
    icon: '🛡️',
    maxPurchases: 3,
  },
  {
    id: 'specialty-vip-badge',
    name: 'VIP Access Badge',
    description: 'Access any floor regardless of career level for 24h.',
    category: 'specialty',
    cost: 5000,
    requiredLevel: 5,
    icon: '🎫',
    maxPurchases: 1,
  },
  {
    id: 'specialty-double-xp-weekend',
    name: 'Double XP Weekend',
    description: 'All XP rewards doubled for the next 48 hours of game time.',
    category: 'specialty',
    cost: 8000,
    requiredLevel: 7,
    icon: '🔥',
    buff: { type: 'xp_multiplier', value: 2.0, isFlat: false },
    maxPurchases: 1,
  },
  {
    id: 'specialty-lifetime-warranty',
    name: 'Lifetime Warranty',
    description: 'All consumables purchased after this are 25% cheaper. Stacks with hint discount.',
    category: 'specialty',
    cost: 10000,
    requiredLevel: 8,
    icon: '⭐',
    buff: { type: 'hint_discount', value: 25, isFlat: true },
    maxPurchases: 1,
  },
];

export const SHOP_CATEGORIES: { id: ShopCategory; label: string; icon: string }[] = [
  { id: 'office-upgrade', label: 'Office Upgrades', icon: '🏢' },
  { id: 'certification', label: 'Certifications', icon: '🎓' },
  { id: 'tool', label: 'Tools', icon: '🔧' },
  { id: 'consumable', label: 'Consumables', icon: '🧪' },
  { id: 'cosmetic', label: 'Cosmetics', icon: '🎨' },
  { id: 'specialty', label: 'Specialty', icon: '⭐' },
];

export function getShopItem(id: string): ShopItem | undefined {
  return SHOP_ITEMS.find(item => item.id === id);
}

export function getItemsByCategory(category: ShopCategory): ShopItem[] {
  return SHOP_ITEMS.filter(item => item.category === category);
}

export function getItemsByLevel(maxLevel: number): ShopItem[] {
  return SHOP_ITEMS.filter(item => item.requiredLevel <= maxLevel);
}
